### ISSUE TITLE
Friend Link Request: NoneBot

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#19]
{
    "name": "无机器人",
    "name_en": "NoneBot",
    "des": "跨平台蟒蛇异步机器人框架",
    "des_en": "Cross platform Python asynchronous bot framework",
    "url": "https://nonebot.dev/",
    "icon": "https://nonebot.dev/logo.png",
    "lang": "zh"
}

**Comment by snowykami** [comment]
✅ 预检查完成，等待仓库所有者审核

**链接**: [https://nonebot.dev/](https://nonebot.dev/)


**标题**: NoneBot


**描述**: No description found


**延迟**: 126.00ms

🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
✅ 预检查完成，等待仓库所有者审核

**链接**: [https://nonebot.dev/](https://nonebot.dev/)


**标题**: NoneBot


**描述**: No description found


**延迟**: 103.00ms

🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
✅ 预检查完成，等待仓库所有者审核

# 申请信息

**链接**: [https://nonebot.dev/](https://nonebot.dev/)

**站点名称**: NoneBot/NoneBot

**描述**: 跨平台 Python 异步机器人框架/NoneBot


# 查询结果

**标题**: NoneBot

**描述**: No description found

**延迟**: 78.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
Approved

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://nonebot.dev/](https://nonebot.dev/)

**站点名称**: NoneBot / No English name

**描述**: 跨平台 Python 异步机器人框架 / Cross platform Python asynchronous bot framework


# 查询结果

**标题**: NoneBot

**描述**: No description found

**延迟**: 108.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://nonebot.dev/](https://nonebot.dev/)

**站点名称**: 无机器人 / NoneBot

**描述**: 跨平台 Python 异步机器人框架 / Cross platform Python asynchronous bot framework


# 查询结果

**标题**: NoneBot

**描述**: No description found

**延迟**: 336.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://nonebot.dev/](https://nonebot.dev/)

**站点名称**: 无机器人 / NoneBot

**描述**: 跨平台蟒蛇异步机器人框架 / Cross platform Python asynchronous bot framework


# 查询结果

**标题**: NoneBot

**描述**: No description found

**延迟**: 124.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
