### ISSUE TITLE
Friend Link Request: NoneBotX

### ISSUE THREAD

**Issue by KomoriDev** [snowykami/blog#20]
{
    "name": "无机器人X",
    "name_en": "NoneBotX",
    "des": "无机器人 社区文档",
    "des_en": "NoneBot community docs",
    "url": "https://x.none.bot",
    "icon": "https://x.none.bot/favicon.png",
    "lang": "zh"
}

**Comment by snowykami** [comment]
✅ 预检查完成，等待仓库所有者审核

# 申请信息

**链接**: [https://x.none.bot](https://x.none.bot)

**站点名称**: NoneBotX / No English name

**描述**: NoneBot 社区文档 / No English description


# 查询结果

**标题**: 主页 | NoneBot 文档

**描述**: NoneBot2 社区文档

**延迟**: 309.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
OK

**Comment by snowykami** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
