### ISSUE TITLE
Friend Link Request: MeloBot

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#21]
{
    "name": "梅洛机器人",
    "name_en": "MeloBot",
    "des": "支持多协议、多路输入输出与其他高级特性的机器人开发框架",
    "des_en": "A bot development framework that supports multiple protocols, multi-channel IO, and other advanced features.",
    "url": "https://docs.melobot.org/",
    "icon": "https://docs.melobot.org/_static/logo.png",
    "lang": "en"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查完成，等待仓库所有者审核

# 申请信息

**链接**: [https://docs.melobot.org/](https://docs.melobot.org/)

**站点名称**: MeloBot / No English name

**描述**: 支持多协议、多路 IO 与其他高级特性的机器人开发框架 / No English description


# 查询结果

**标题**: melobot 2.6.5

**描述**: No description found

**延迟**: 628.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

    # 申请信息

    **链接**: [https://docs.melobot.org/](https://docs.melobot.org/)

    **站点名称**: MeloBot / No English name

    **描述**: 支持多协议、多路 IO 与其他高级特性的机器人开发框架 / No English description


    # 查询结果

    **标题**: melobot 2.6.5

    **描述**: No description found

    **延迟**: 229.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting property name enclosed in double quotes: line 4 column 125 (char 194)，请修改issue

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

    # 申请信息

    **链接**: [https://docs.melobot.org/](https://docs.melobot.org/)

    **站点名称**: MeloBot / No English name

    **描述**: 支持多协议、多路 IO 与其他高级特性的机器人开发框架 / No English description


    # 查询结果

    **标题**: melobot 2.6.5

    **描述**: No description found

    **延迟**: 55.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://docs.melobot.org/](https://docs.melobot.org/)

**站点名称**: MeloBot / No English name

**描述**: 支持多协议、多路 IO 与其他高级特性的机器人开发框架 / No English description


# 查询结果

**标题**: melobot 2.6.5

**描述**: No description found

**延迟**: 376.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://docs.melobot.org/](https://docs.melobot.org/)

**站点名称**: MeloBot / No English name

**描述**: 支持多协议、多路 IO 与其他高级特性的机器人开发框架 / A bot development framework that supports multiple protocols, multi-channel IO, and other advanced features.


# 查询结果

**标题**: melobot 2.6.5

**描述**: No description found

**延迟**: 343.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
OK

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 2 column 13 (char 15)，请修改issue

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 2 column 13 (char 15)，请修改issue

**Comment by liteyuki-flow** [comment]
✅ Pre-check passed, ready to go, waiting for the repository owner to review

# Apply Info

**URL**: [https://docs.melobot.org/](https://docs.melobot.org/)

**Site Name**: 梅洛机器人 / MeloBot

**Description**: 支持多协议、多路输入输出与其他高级特性的机器人开发框架 / A bot development framework that supports multiple protocols, multi-channel IO, and other advanced features.


# Query Result

**Title**: melobot 2.6.5

**Description**: No description found

**Ping**: 382.00ms
🌐 Do you want to add internationalization data? If you want, please modify the issue to add `name_en` and `des_en` fields.

**Comment by liteyuki-flow** [comment]
✅ Check passed, the friend link has been added, and the page will be built soon.

**Comment by liteyuki-flow** [comment]
Admin did not pass

**Comment by snowykami** [comment]
通过
