### ISSUE TITLE
Friend Link Request: 旧梦流年

### ISSUE THREAD

**Issue by ElapsingDreams** [snowykami/blog#23]
{
    "name": "旧梦流年",
    "name_en": "ElapsingDreams",
    "des": "喵~",
    "des_en": "ElapsingDreams's github",
    "url": "https://github.com/ElapsingDreams",
    "icon": "https://github.com/ElapsingDreams.png"}

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Unterminated string starting at: line 5 column 13 (char 103)，请修改issue

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting ',' delimiter: line 5 column 70 (char 160)，请修改issue

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://github.com/ElapsingDreams](https://github.com/ElapsingDreams)

**站点名称**: 旧梦流年 / No English name

**描述**: 喵~ / No English description


# 查询结果

**标题**: ElapsingDreams (ElapsingDreams) · GitHub

**描述**: ElapsingDreams has 6 repositories available. Follow their code on GitHub.

**延迟**: 218.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://github.com/ElapsingDreams](https://github.com/ElapsingDreams)

**站点名称**: 旧梦流年 / No English name

**描述**: 喵~ / No English description


# 查询结果

**标题**: ElapsingDreams (ElapsingDreams) · GitHub

**描述**: ElapsingDreams has 6 repositories available. Follow their code on GitHub.

**延迟**: 155.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://github.com/ElapsingDreams](https://github.com/ElapsingDreams)

**站点名称**: 旧梦流年 / No English name

**描述**: 喵~ / No English description


# 查询结果

**标题**: ElapsingDreams (ElapsingDreams) · GitHub

**描述**: ElapsingDreams has 6 repositories available. Follow their code on GitHub.

**延迟**: 257.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://github.com/ElapsingDreams](https://github.com/ElapsingDreams)

**站点名称**: 旧梦流年 / No English name

**描述**: 喵~ / No English description


# 查询结果

**标题**: ElapsingDreams (ElapsingDreams) · GitHub

**描述**: ElapsingDreams has 6 repositories available. Follow their code on GitHub.

**延迟**: 200.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://github.com/ElapsingDreams](https://github.com/ElapsingDreams)

**站点名称**: 旧梦流年 / ElapsingDreams

**描述**: 喵~ / ElapsingDreams's github


# 查询结果

**标题**: ElapsingDreams (ElapsingDreams) · GitHub

**描述**: ElapsingDreams has 6 repositories available. Follow their code on GitHub.

**延迟**: 237.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
修改成功

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
