### ISSUE TITLE
Friend Link Request: 粥里有勺糖

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#24]
{
    "name": "粥里有勺糖",
    "des": "粥里有勺糖的博客",
    "url": "https://sugarat.top/",
    "name_en": "sugarat's blog",
    "des_en": "sugarat's front-end blog",
    "icon": "https://cdn.upyun.sugarat.top/avatar/blog/zlyst-avatar.jpeg-wh100",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://sugarat.top/](https://sugarat.top/)

**站点名称**: 粥里有勺糖 / No English name

**描述**: 粥里有勺糖的博客 / No English description


# 查询结果

**标题**: 粥里有勺糖

**描述**: 粥里有勺糖的个人博客，记录随笔与学习笔记，大前端相关的知识，高频面试题，个人面经等

**延迟**: 336.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://sugarat.top/](https://sugarat.top/)

**站点名称**: 粥里有勺糖 / sugarat's blog

**描述**: 粥里有勺糖的博客 / sugarat's blog


# 查询结果

**标题**: 粥里有勺糖

**描述**: 粥里有勺糖的个人博客，记录随笔与学习笔记，大前端相关的知识，高频面试题，个人面经等

**延迟**: 429.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://sugarat.top/](https://sugarat.top/)

**站点名称**: 粥里有勺糖 / sugarat's blog

**描述**: 粥里有勺糖的博客 / sugarat's front-end blog


# 查询结果

**标题**: 粥里有勺糖

**描述**: 粥里有勺糖的个人博客，记录随笔与学习笔记，大前端相关的知识，高频面试题，个人面经等

**延迟**: 182.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
