### ISSUE TITLE
Friend Link Request: 艾拉酱小屋

### ISSUE THREAD

**Issue by luosheng520qaq** [snowykami/blog#25]
{
    "name": "艾拉酱小屋",
    "des": "QQbot艾拉酱的小破站",
    "url": "https://www.isla.ltd",
    "icon": "https://c-ssl.duitang.com/uploads/blog/202203/25/20220325220854_59aa8.thumb.400_0.jpg",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://www.isla.ltd](https://www.isla.ltd)

**站点名称**: 艾拉酱小屋 / No English name

**描述**: QQbot艾拉酱的小破站 / No English description


# 查询结果

**标题**: 
			灿の小破站
		

**描述**: No description found

**延迟**: 938.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
Approved

**Comment by snowykami** [comment]
第二次通过
