### ISSUE TITLE
Friend Link Request: daoge的github主页

### ISSUE THREAD

**Issue by smartcmd** [snowykami/blog#28]
{
    "name": "daoge的github主页",
    "des": "喵喵喵",
    "url": "https://github.com/smartcmd",
    "icon": "https://avatars.githubusercontent.com/u/60499296?v=4",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://github.com/smartcmd](https://github.com/smartcmd)

**站点名称**: daoge的github主页 / No English name

**描述**: 喵喵喵 / No English description


# 查询结果

**标题**: smartcmd (daoge) · GitHub

**描述**: Programmer & Student From China. smartcmd has 30 repositories available. Follow their code on GitHub.

**延迟**: 286.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
无法获取关闭者信息

**Comment by liteyuki-flow** [comment]
无法获取关闭者信息

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
