### ISSUE TITLE
Friend Link Request: 轻雪铁路

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#29]
{
    "name": "轻雪铁路",
    "name_en": "LMTR",
    "des": "轻雪铁路工作室 - Minecraft Rail Transit",
    "des_en": "Liteyuki Minecraft Rail Transit",
    "url": "https://mtr.lite.ac.cn/",
    "icon": "https://mtr.lite.ac.cn/favicon.ico",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://mtr.lite.ac.cn/](https://mtr.lite.ac.cn/)

**站点名称**: 轻雪铁路 / No English name

**描述**: 轻雪铁路工作室 - Minecraft Rail Transit / No English description


# 查询结果

**标题**: 轻铁 | LMTR

**描述**: No description found

**延迟**: 339.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：404 {"message": "Label does not exist", "documentation_url": "https://docs.github.com/rest/issues/labels#remove-a-label-from-an-issue", "status": "404"}，请修改issue

**Comment by liteyuki-flow** [comment]
无法获取关闭者信息

**Comment by liteyuki-flow** [comment]
无法获取关闭者信息

**Comment by liteyuki-flow** [comment]
管理员未审核

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://mtr.lite.ac.cn/](https://mtr.lite.ac.cn/)

**站点名称**: 轻雪铁路 / LMTR

**描述**: 轻雪铁路工作室 - Minecraft Rail Transit / Liteyuki Minecraft Rail Transit


# 查询结果

**标题**: 轻铁 | LMTR

**描述**: No description found

**延迟**: 346.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
