### ISSUE TITLE
Friend Link Request: 逝与逢博客

### ISSUE THREAD

**Issue by zouXH-god** [snowykami/blog#30]
{
    "name": "逝与逢博客",
    "des": "逝染的个人博客",
    "url": "https://blog.xin-hao.top",
    "icon": "https://blog.xin-hao.top/wp-content/uploads/2023/10/log.png",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://blog.xin-hao.top](https://blog.xin-hao.top)

**站点名称**: 逝与逢博客 / No English name

**描述**: 逝染的个人博客 / No English description


# 查询结果

**标题**: 逝&逢-一个简单的技术博客

**描述**: 

**延迟**: 526.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
