### ISSUE TITLE
Friend Link Request: Inkar Suki

### ISSUE THREAD

**Issue by HornCopper** [snowykami/blog#31]
{
    "name": "Inkar Suki",
    "des": "基于无机器人貳(一个机器人微拾壹)开发的群机器人",
    "url": "https://inkar-suki.codethink.cn/Inkar-Suki-Docs/",
    "icon": "https://inkar-suki.codethink.cn/Inkar-Suki-Docs/img/InkarSukiCopyright.png",
    "des_en": "A Bot based on NoneBot 2(OneBot V11 Standard) with developed for group chat."
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://inkar-suki.codethink.cn/Inkar-Suki-Docs/](https://inkar-suki.codethink.cn/Inkar-Suki-Docs/)

**站点名称**: Inkar Suki / No English name

**描述**: 基于无机器人貳(一个机器人微拾壹)开发的群机器人 / No English description


# 查询结果

**标题**: Inkar Suki 官方文档 - CodeThink

**描述**: Description

**延迟**: 22.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://inkar-suki.codethink.cn/Inkar-Suki-Docs/](https://inkar-suki.codethink.cn/Inkar-Suki-Docs/)

**站点名称**: Inkar Suki / No English name

**描述**: 基于无机器人貳(一个机器人微拾壹)开发的群机器人 / A Bot based on NoneBot 2(OneBot V11 Standard) with developed for group chat.


# 查询结果

**标题**: Inkar Suki 官方文档 - CodeThink

**描述**: Description

**延迟**: 933.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
