### ISSUE TITLE
Trend: 测试动态1

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#36]
这是一条测试动态
![380206](https://github.com/user-attachments/assets/58993296-bbe7-4d31-81c6-be7e9dad33b1)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
