### ISSUE TITLE
基于github issue的博客动态系统+云函数api请求

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#38]
这个功能是我临时想出来，能不能做一个和QQ空间那样的功能，但是又不用每次创建一个页面，也不依赖自建服务器。于是便想到了github的issue功能，自带标题，身体部分，很适合作为写动态的地方，而且还自带图床。简直就是一个完美的发动态工具。于是这个东西便应运而生。github api在没有认证的情况下有速率限制，但是在前端存token是不安全的，我们可以把token和请求中转部署到云函数上面，减少github 被盗用的风险

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue

**Comment by snowykami** [comment]
未来将会把这个功能拆出来，做成独立功能供大家使用
