### ISSUE TITLE
基于nonebot2的插件商店插件

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#42]
最近突发奇想把轻雪机器人中的npm的插件管理功能的安装部分抽离出来做成一个nonebot插件，于是就有了这个新插件，还在开发中
地址：[nonebot-plugin-nps](https://github.com/snowykami/nonebot-plugin-nps)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue

**Comment by snowykami** [comment]
回复
