### ISSUE TITLE
群友团建

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#43]
![IMG_20240903_194845.jpg](https://github.com/user-attachments/assets/5a61fcdb-0202-41a2-9b1a-8cb432ca062d)

![IMG_20240903_194007.jpg](https://github.com/user-attachments/assets/fae2ea8a-99df-4cce-a862-b6e9124ca0ed)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
