### ISSUE TITLE
部门团建
Redrock!

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#44]
![IMG_20240928_210816.jpg](https://github.com/user-attachments/assets/96dc743b-2d34-45d0-a13a-9e0d37dd666e)

![IMG_20240928_210635.jpg](https://github.com/user-attachments/assets/3b354c8f-8c55-4f0f-a68e-e1d7ecb5d771)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
