### ISSUE TITLE
Friend Link Request: 一楼没太阳

### ISSUE THREAD

**Issue by Msg-Lbo** [snowykami/blog#46]
{
    "name": "一楼没太阳",
    "des": "只有坏掉的东西才会停下来",
    "url": "https://blog.ylmty.cc",
    "icon": "https://q1.qlogo.cn/g?b=qq&nk=24130801&s=100"
}

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Invalid control character at: line 5 column 40 (char 129)，请修改issue

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://blog.ylmty.cc](https://blog.ylmty.cc)

**站点名称**: 一楼没太阳 / No English name

**描述**: 只有坏掉的东西才会停下来 / No English description


# 查询结果

**标题**: 一楼没太阳

**描述**: No description found

**延迟**: 331.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
