### ISSUE TITLE
三天开发了一个服务器探针

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#48]
国庆前三天在家没事干的
一个基于Python的服务器探针
需要部署一个go编写的服务器统计数据
服务端：[server-status-server](https://github.com/snowykami/server-status-server)
客户端：[server-status-client](https://github.com/snowykami/server-status-client)
欢迎各位的贡献和star
![{70903E75-C8FF-418f-B817-89F28D40C375}.png](https://github.com/user-attachments/assets/3383661b-8b37-42ad-8eba-2156a35b6fcb)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
