### ISSUE TITLE
面基

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#49]
![IMG_20241006_135935.jpg](https://github.com/user-attachments/assets/a310bbe1-f7b3-46bf-8e96-b079d67cd1a8)

![IMG_20241006_140101.jpg](https://github.com/user-attachments/assets/53536d35-ab4e-4870-a042-8c84ae04956d)

![IMG_20241006_134858.jpg](https://github.com/user-attachments/assets/293cb4a8-868f-425a-bece-1ad10ef72fe4)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
