### ISSUE TITLE
Friend Link Request: eya46

### ISSUE THREAD

**Issue by eya46** [snowykami/blog#51]
{
    "name": "eya46",
    "des": "eya46的主页",
    "url": "https://eya46.com",
    "icon": "https://github.com/eya46.png",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://eya46.com](https://eya46.com)

**站点名称**: eya46 / No English name

**描述**: eya46的主页 / No English description


# 查询结果

**标题**: eya46 – 个人学习主页

**描述**: 个人学习主页

**延迟**: 40.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
