### ISSUE TITLE
也是见到大佬本人了

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#52]
从21年到23年一直在用gocq作为我的机器人的实现端，今天也算是见到[Mrs4s](https://github.com/Mrs4s)本人了。一起恰了一顿烤肉，大家都聊的很愉快。
![IMG_20241028_023530.jpg](https://github.com/user-attachments/assets/b8d7f412-2784-4759-9966-f73724b50518)

![IMG_20241027_192059.jpg](https://github.com/user-attachments/assets/afa471ff-7ee3-4acf-8ce3-dc61d381976d)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
