### ISSUE TITLE
开始学习Rust...

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#53]
你邮太先进了，开了个Rust程序设计(必修)。据我所知国内外高校目前没多少开原神语言的课程的，再加上非计科专业，buff叠满了。![Image_36305522572191.jpg](https://github.com/user-attachments/assets/510024c5-4207-4a96-9402-df774eee5ace)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
