### ISSUE TITLE
Liteyuki Gitea服务全新升级

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#54]
基于gitea二次修改开发的定制版本

- 相比github，在中国大陆连通性更佳，可作为中转或镜像仓库使用
- 使用高速转接服务器提升https web服务速度，网页响应速度更快
- 启用ssh直连，使用密钥对作为身份凭据，延迟低且带宽高
- 丰富的主题可供选择
- 优化了act-runner的科学联网策略，自动化工作流效率更高
- 所有仓库均有主从备份，防止数字作品丢失(备份服务为每天4:00进行)
- actions registry提供一系列常用的镜像可供选择，也可自行推送镜像使用
- 与Liteyuki docker无缝集成

> 该服务为私人服务，如想申请账号可发送邮件至snowykami@liteyuki.icu，附带上你的**邮箱**，**用户名**

![Screenshot_2024-11-02_20-48-17.png](https://github.com/user-attachments/assets/3c0fc62c-d610-438b-b31f-63897dbee0bd)
![Screenshot_2024-11-02_20-45-23.png](https://github.com/user-attachments/assets/32d5f8fd-0922-42a7-b114-a704b232f3b0)

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
