### ISSUE TITLE
推歌 「苹果香」

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#55]
大晚上被蟑螂吓清醒了，睡不着，打开b站，看到此曲![Screenshot_2024-11-06-04-46-14-883_tv.danmaku.bili.jpg](https://github.com/user-attachments/assets/13326af5-511c-43e6-ae21-831ea4692e61)

@liteyuki-flow

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
