### ISSUE TITLE
使一颗心免于哀伤(本人翻译版本)

### ISSUE THREAD

**Issue by snowykami** [snowykami/blog#56]
当初做红石音乐自己翻译的一个中文版，感觉还不错

Birds are born with no shackles，
> 鸟本生无羁
Then what fetters my fate?
> 何物缚吾命
Blown away, the white petals，
> 白花随风散
Leave me trapped in the cage.
The endless isolation，
Can't wear down my illusion，
Someday, I’ll make a dream unchained，
Let my heart bravely spread the wings，
Soaring past the night，
To trace the bright moonlight，
Let the clouds heal me of the stings，
Gently wipe the sorrow off my life，
I dream，
What is meant by “miracle”,
A word outside my days?
Once again, repeat warbles，
But how could I escape?
No further hesitation，
On those unanswered questions，
So now, I’ll make a dream unchained，
Let my heart bravely spread the wings，
Soaring past the night，
To trace the bright moonlight，
Let the clouds heal me of the stings，
Gently wipe the sorrow off my life，
I dream，
Let my heart bravely spread the wings，
Soaring past the night，
To trace the bright moonlight，
Let the clouds heal me of the stings，
Gently wipe the sorrow off my life，
I dream，
I dream。

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue

**Comment by liteyuki-flow** [comment]
❌ 预检查未通过：Expecting value: line 1 column 1 (char 0)，请修改issue
