### ISSUE TITLE
Friend Link Request: 笨蛋弥生的平行世界

### ISSUE THREAD

**Issue by Fjaxzhy** [snowykami/blog#57]
{
    "name": "笨蛋弥生的平行世界",
    "des": "创造生命的逃逸之线",
    "url": "https://blog.kagurayayoi.top",
    "icon": "https://blog.kagurayayoi.top/favicon/cropped-icon.jpg",
    "lang": "zh"
}

**Comment by liteyuki-flow** [comment]
✅ 预检查通过，一切工作已就绪，等待仓库所有者审核

# 申请信息

**链接**: [https://blog.kagurayayoi.top](https://blog.kagurayayoi.top)

**站点名称**: 笨蛋弥生的平行世界 / No English name

**描述**: 创造生命的逃逸之线 / No English description


# 查询结果

**标题**: 笨蛋弥生的平行世界 - 创造生命的逃逸之线

**描述**: 笨蛋弥生的平行世界 - 创造生命的逃逸之线

**延迟**: 52.00ms
🌐 是否添加国际化数据？如需添加请修改issue添加`name_en`、`des_en`字段。

**Comment by snowykami** [comment]
通过

**Comment by liteyuki-flow** [comment]
✅ 审核通过，已添加友链，页面稍后就会构建好
