### ISSUE TITLE
Friend Link Request: 旧梦流年

### ISSUE THREAD

**Issue by ElapsingDreams** [snowykami/blog#7]
{
    "name": "旧梦流年",
    "des": "旧梦流年test",
    "url": "https://git.liteyuki.icu/ElapsingDreams",
    "icon": "https://git.liteyuki.icu/avatars/3b0fe4e825dfda58cdedf111b8e81bfee94a536f0b095a1dd4fd8aad3226b282?size=512"
}

**Comment by snowykami** [comment]
✅ 预检查完成，等待仓库所有者审核

**Comment by snowykami** [comment]
✅ 审核通过，已添加友链，网页稍后就会构建好
